### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by bald-head** [xams-creator/navicat-resetter#1]
您好：
    请问在mac下面有什么办法能够重置试用吗？

**Comment by xams-creator** [comment]
目前因为虚拟机没装Mac环境，所以年前是没计划支持Mac的。

主要还是会以容易实现的Linux和Windows为主，抱歉。

这里有篇文章里有彻底卸载Mac Navicat for Mysql的方法，不知道能不能用，如果尝试后可以用，麻烦回复我下，谢谢哦！

https://blog.csdn.net/zl199104/article/details/51055557/

**Comment by bald-head** [comment]
您好！
   我暂时没有卸载的需求！我有win  VMWare安装macos的资料，有需要可以联系我提供

**Comment by bald-head** [comment]
> 装Mac环境，所以年前是没计划支持Mac的。
> 
> 主要还是会以容易实现的Linux和Windows为主，抱歉。
> 
> 这里有篇文章里有彻底卸载Mac Navicat
